### ISSUE TITLE
Multiple Choice Questions in Exercise Sections Don't "Complete"

### ISSUE THREAD

**Issue by ForrestStevens** [barbarer/py4e-int#42]
I'm unsure whether it's a problem with Runestone's implementation of the text or a problem in the way that the Exercise sections are organized, but my students brought it to my attention that the Exercise sections don't contain a "Mark Complete" button and never register in the progress pages as Completed. They are always "never started," however they are recorded in the grade book.

**Comment by barbarer** [comment]
You are correct that the Exercises subchapter does not have a mark complete
button.  Brad can probably better answer why.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by barbarer** [comment]
It is a feature, not a bug.  😀. Many of our Exercises pages contain exercises from the author as well as contributed exercises from instructors.  In some cases the exercises page may have hundreds of them. It would be highly unusual for someone to assign ALL of the exercises on a page that big.  Even my own books I add far more exercises than I would expect someone to assign.

The mark complete button has absolutely nothing to do with points for reading assignments.  Students cannot trick the system into thinking they have done all of the required activities just by clicking the button though many of them think they can.

In my books I exclude all of the Exercises pages from being included in the list of pages that you can select for a reading assignment.  I’ve always viewed the Exercises pages as the place to put questions you want to grade, rather than a place you want students to just click the run button.

Hope that helps.

Brad

Bradley Miller, PhD
Professor Emeritus Computer Science
Luther College
Founder, Runestone Interactive
Blog: A Reputable Journal

Democratizing Textbooks for the 21st Century - Please Support Runestone

**Comment by ForrestStevens** [comment]
I guess it's non-intuitive that this particular section, which can be assigned as a "Reading," as opposed to individually chosen "Problems" should function any differently than the Mixed-Up Code or Write Code sections. That's where my confusion stemmed from.

**Comment by bnmnetp** [comment]
@barbarer If you would like to exclude the Exercises pages from reading assignments you can add this line at the top of the Exercises.rst pages.

```
:skipreading:`True`
```
